### ISSUE TITLE
Investigate decoding WebCodecs 'opus' encoded audio buffer

### ISSUE THREAD

**Issue by guest271314** [AnthumChris/opus-stream-decoder#20]
WebCodecs https://github.com/WICG/web-codecs/blob/master/explainer.md implements `'opus'` encoder configuration https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/webcodecs/audio_encoder.cc;l=8.

I have tried to playback the encoded chunks at `HTMLAudioElement`, `ffmpeg`, and `mpv` without success https://bugs.chromium.org/p/chromium/issues/detail?id=1180089.

Given you are involved in decoding Opus for the Web I ask for your assessment of precisely how the audio is encoded (is the encoding non-standard compared to using `opusenc`) and how to decode the encoded audio without using `AudioDecoder`?

**Comment by AnthumChris** [comment]
Thanks for writing. I'm going to close this issue as it's not directly related to this repo.

**Comment by guest271314** [comment]
@AnthumChris This is a feature request for this repositry to support decoding "raw compressed packets" produced by WebCodecs `AudioEncoder`.
