### ISSUE TITLE
Mono

### ISSUE THREAD

**Issue by ktb92677** [AnthumChris/opus-stream-decoder#21]
What happens if the opus stream is in mono? Which channel should I use left or right?

**Comment by anthumchris** [comment]
I honestly don't remember if mono was tested with this or not.  I do remember that you'll always get decoded stereo float samples back though.

**Comment by ktb92677** [comment]
So the decoder always returns a left and right channel... since the audio is in mono will using either one work?

**Comment by anthumchris** [comment]
Unfortunately, I'm not sure and it's been a couple years since I tested with files. I would encourage you to test with a mono/stereo file to see what happens.  I won't have time to do that unfortunately.

**Comment by atulbari-samespace** [comment]
@ktb92677 
How to play received left and right buffer in browser??
In onDecode,
I tried with audio element as
audioelement.src = left;
audioelement.load()

**Comment by anthumchris** [comment]
@atulbari-samespace Hi there.  This repo is a WebAssembly module, and I recommend using the [StackOverflow `web-audio-api`](https://stackoverflow.com/questions/tagged/web-audio-api) tag to post questions and search answers. Sorry I can't be of much help here!
