### ISSUE TITLE
Streaming audio output/live

### ISSUE THREAD

**Issue by zzph** [AnthumChris/opus-stream-decoder#24]
Hi there,

Apologies if this is a basic question.

I'm trying to "stream" audio from my PC. Latency isn't super important.

Despite efforts with WebRTC, and modifying the codec/quality- the sound quality is poor.

If i find a way to "stream" to a file, can your library stream the file even though it hasn't been fully "created" yet?

Or did you have another suggestion on how to achieve this?

Thanks :)

**Comment by anthumchris** [comment]
I apologize, but I'm not sure how to answer your question.  I would recommend StackOverflow to field opinions. Their community is great and extremely helpful.  I'm going to close this issue because it's not specific to this code repo.
