### ISSUE TITLE
play it in <audio>

### ISSUE THREAD

**Issue by elshnkhll** [AnthumChris/opus-stream-decoder#25]
I am receiving stereo 48KHZ Opus encoded audio in in variable (~170 byte) size 20ms chunks extracted from UDP/RTP packets. Can your decoder play it in <audio>? An example code would be appreciated.  Regards.

**Comment by anthumchris** [comment]
The decoder works with Ogg Opus files ([RFC 7845](https://datatracker.ietf.org/doc/html/rfc7845)), and the "encoded audio" must be the Ogg file itself.

Consider using the newer [WebCodecs API](https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API) to potentially decode raw Opus audio (not encapsulated within Ogg).

For use within `<audio>`, please see [Media Capture and Streams API (Media Stream)](https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API)

**Comment by elshnkhll** [comment]
Thanks.

**Comment by elshnkhll** [comment]
Thanks
