### ISSUE TITLE
Wait to fix opus file implicit conversion?

### ISSUE THREAD

**Issue by briancullinan** [AnthumChris/opus-stream-decoder#8]
I'm using a pretty strict Makefile from ioquake/ioq3, it has -Werror set, is there a way to fix the 
```
code/opusfile-0.9/src/opusfile.c:3228:18: error: implicit conversion from
      'unsigned int' to 'float' changes value from 4294967295 to 4294967296
      [-Werror,-Wimplicit-int-float-conversion]
          r=seed*OP_PRNG_GAIN;
                 ^~~~~~~~~~~~
code/opusfile-0.9/src/opusfile.c:3165:29: note: expanded from macro
      'OP_PRNG_GAIN'
# define OP_PRNG_GAIN (1.0F/0xFFFFFFFF)
                           ~^~~~~~~~~~
code/opusfile-0.9/src/opusfile.c:3230:19: error: implicit conversion from
      'unsigned int' to 'float' changes value from 4294967295 to 4294967296
      [-Werror,-Wimplicit-int-float-conversion]
          r-=seed*OP_PRNG_GAIN;
                  ^~~~~~~~~~~~
code/opusfile-0.9/src/opusfile.c:3165:29: note: expanded from macro
      'OP_PRNG_GAIN'
# define OP_PRNG_GAIN (1.0F/0xFFFFFFFF)
                           ~^~~~~~~~~~
2 errors generated.
```

??? I am pretty new to C, I tried using a union like the docs said, but the sound that plays it just a buzz, like it's spiked out of range, given the calculations in the code that seems to make sense, 
https://github.com/briancullinan/planet_quake/blob/ioq3-quakejs/code/opusfile-0.9/src/opusfile.c#L3196

**Comment by AnthumChris** [comment]
Hi @briancullinan.  I'm not knowledgable enough to answer this and since it's specific to the Opus codebase and not this repo, I recommend reaching out to the official Opus mailing list: http://lists.xiph.org/mailman/listinfo/opus

Sorry I can't be of more assistance!
